import Value from "@/components/About/Value/Value";
import Button from "@/components/Common/Button";
import { Arrow } from "@/components/Header/Icons";
import Hero from "@/components/Home/Hero/Hero";
import Started from "@/components/Home/Started/Started";
import Work from "@/components/Home/Work/Work";
import { aboutData } from "@/components/Home/Work/data";
import axios from "axios";
import type { GetStaticProps } from "next";
import { useTranslations } from "next-intl";
import Head from "next/head";

const AboutPage = () => {
  const t = useTranslations("About");
  const tx = useTranslations("About.Our-Mission-Section");

  return (
    <>
      <Head>
        <title>ProCupp - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero bgSrc="/about/hero-bg.png">
        <h1>{t("Hero-Section.Heading")}</h1>
        <p>{t("Hero-Section.Paragraph")}</p>
      </Hero>
      <Work
        heading={t("Our-Mission-Section.Heading")}
        tag={t("Our-Mission-Section.Tag")}
        data={aboutData}
        t={tx}
      />
      <Value />
      {/* <Started
        direction="right"
        imgSrcOne="/home/started-images/0.png"
        imgSrcTwo="/home/started-images/1.png"
      >
        <h2>Get Started For Free</h2>
        <p>
          Massa urna arcu dolor elit vel in augue. Tempor egestas sed turpis
          posuere dolor erat. Bibendum facilisis neque amet enim quisque egestas
          sit.
        </p>

        <Button>
          Get Started <Arrow />
        </Button>
      </Started> */}
    </>
  );
};

export default AboutPage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
