import ChooseUs from "@/components/Home/ChooseUs/ChooseUs";
import Hero from "@/components/Home/Hero/Hero";
import Work from "@/components/Home/Work/Work";
import { homeData } from "@/components/Home/Work/data";
import Selection from "@/components/Products/Selection/Selection";
import type { GetStaticProps } from "next";
import Head from "next/head";
import { useTranslations } from "next-intl";
import axios from "axios";

export default function Home() {
  const t = useTranslations("Home");
  const tx = useTranslations("Home.How-It-Work-Section");

  return (
    <>
      <Head>
        <title>ProCupp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero isVideo>
        <h1>{t("Hero-Section.Heading")}</h1>
        <p>{t("Hero-Section.Paragraph")}</p>
      </Hero>
      <Work
        heading={t("How-It-Work-Section.Heading")}
        tag={t("How-It-Work-Section.Tag")}
        data={homeData}
        t={tx}
      />
      <Selection removePadding />
      <ChooseUs />
      {/* <Question
        heading="How close is this moment when you will drink from the designed cups?"
        imgSrcOne="/common/question-images/0.png"
        imgSrcTwo="/common/question-images/1.png"
      >
        <p>
          Very Close! We deliver within __ to __ days depending on print types
          and quantities.
        </p>
        <p>
          When the order is placed, a shipping number will be sent to the e-mail
          box registered in the system with which the status of the shipment can
          be tracked.
        </p>
        <p>
          When the order is placed, you will receive an order number with which
          you can track the status of the shipment on our website.
        </p>
      </Question> */}

      {/* <Started
        imgSrcOne="/home/started-images/0.png"
        imgSrcTwo="/home/started-images/1.png"
      >
        <h2>Get Started For Free</h2>
        <p>
          Massa urna arcu dolor elit vel in augue. Tempor egestas sed turpis
          posuere dolor erat. Bibendum facilisis neque amet enim quisque egestas
          sit.
        </p>

        <Button>
          Get Started <Arrow />
        </Button>
      </Started> */}
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
