import Banner from "@/components/Common/Banner";
import Description from "@/components/Common/Description";
import axios from "axios";
import type { GetStaticProps } from "next";
import { useTranslations } from "next-intl";
import Head from "next/head";

const PrivacyPolicyPage = () => {
  const t = useTranslations("Privacy-Policy");
  return (
    <>
      <Head>
        <title>ProCupp - Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner heading={t("Banner")} />
      <Description imgSrc="/common/privacy-bg.png" alt="privacy-img">
        <h5>{t("Heading")}</h5>
        <ul>
          <li>{t("Lists.List-0.0")}</li>
          <li>{t("Lists.List-0.1")}</li>
        </ul>
        <ul>
          <h5>{t("Lists.List-1.0")}</h5>
          <li>{t("Lists.List-1.1")}</li>
          <li>{t("Lists.List-1.2")}</li>
        </ul>
        <ul>
          <h5>{t("Lists.List-2.0")}</h5>
          <li>{t("Lists.List-2.1")}</li>
          <li>{t("Lists.List-2.2")}</li>
        </ul>
        <ul>
          <h5>{t("Lists.List-3.0")}</h5>
          <li>{t("Lists.List-3.1")}</li>
        </ul>
        <ul>
          <h5>{t("Lists.List-4.0")}</h5>
          <li>{t("Lists.List-4.1")}</li>
        </ul>
        <ul>
          <h5>{t("Lists.List-5.0")}</h5>
          <li>{t("Lists.List-5.1")}</li>
        </ul>
      </Description>
    </>
  );
};

export default PrivacyPolicyPage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
