import ProductDesign from "@/components/ProductDesign/ProductDesign";
import axios from "axios";
import type { GetStaticProps } from "next";
import Head from "next/head";

const ProductDesignPage = () => {
  return (
    <>
      <Head>
        <title>ProCupp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductDesign />
    </>
  );
};

export default ProductDesignPage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
