import ProfileContainer from "@/components/Profile/ProfileContainer";
import { store } from "@/store";
import axios from "axios";
import type { GetStaticProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useSnapshot } from "valtio";

const ProfilePage = () => {
  const { user } = useSnapshot(store);
  const { push } = useRouter();

  useEffect(() => {
    if (user === undefined) {
      push("/");
    }
  }, [user, push]);

  return (
    <>
      <Head>
        <title>ProCupp - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileContainer />
    </>
  );
};

export default ProfilePage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
