import Banner from "@/components/Common/Banner";
import Question from "@/components/Common/Question/Question";
import Questions from "@/components/Faq/Questions/Questions";
import axios from "axios";
import type { GetStaticProps } from "next";
import Head from "next/head";

const FaqPage = () => {
  return (
    <>
      <Head>
        <title>ProCupp - FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        heading="commitment to excellence and innovation"
        paragraph="We strive to deliver top-notch solutions to meet your unique needs. Whether you're looking for packaging materials, promotional items, or custom branding solutions, ProCupp has you covered."
      />
      <Questions />
      <Question
        heading="How close is this moment when you will drink from the designed cups?"
        imgSrcOne="/common/question-images/0.png"
        imgSrcTwo="/common/question-images/1.png"
      >
        <p>
          Very Close! We deliver within __ to __ days depending on print types
          and quantities.
        </p>
        <p>
          When the order is placed, a shipping number will be sent to the e-mail
          box registered in the system with which the status of the shipment can
          be tracked.
        </p>
        <p>
          When the order is placed, you will receive an order number with which
          you can track the status of the shipment on our website.
        </p>
      </Question>
    </>
  );
};

export default FaqPage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
