import Banner from "@/components/Common/Banner";
import Description from "@/components/Common/Description";
import axios from "axios";
import type { GetStaticProps } from "next";
import { useTranslations } from "next-intl";
import Head from "next/head";

const TermAndConditionPage = () => {
  const t = useTranslations("Terms-And-Conditions");
  return (
    <>
      <Head>
        <title>ProCupp - Terms and Conditions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner heading={t("Banner")} />
      <Description imgSrc="/common/terms-bg.png" alt="terms-and-condition-img">
        <h5>{t("Heading")}</h5>
        {[...Array(10)].map((e, i) => {
          return (
            <ul key={i}>
              <h5>{t(`Lists.List-${i}.0`)}</h5>
              <li>{t(`Lists.List-${i}.1`)}</li>
            </ul>
          );
        })}
      </Description>
    </>
  );
};

export default TermAndConditionPage;

export const getStaticProps: GetStaticProps = async (context) => {
  let messages = await axios.get(
    `${process.env.NEXT_PUBLIC_PAYLOAD_SERVER}/api/languages?where[locale][equals]=${context.locale}`
  );

  return {
    props: {
      messages: messages.data.docs[0].data,
      // messages: (await import(`../messages/${context.locale}.json`)).default,
    },
    revalidate: 60,
  };
};
